"""047_add_user_register_type

Revision ID: a7b8c9d0e1f2
Revises: 8855aea2dd61
Create Date: 2025-11-06 14:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c1b794a961ce'
down_revision = '8855aea2dd61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 添加 register_type 字段到 sys_user 表
    # 0: 系统注册（默认）
    # 1: 4a平台注册
    # 2: 钉钉用户注册
    op.add_column('sys_user', sa.Column('register_type', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sys_user', 'register_type')
    # ### end Alembic commands ###

