"""057_fix_identity_generated_always

将 chat_execution_trace 的 id 列从 GENERATED ALWAYS 改为 GENERATED BY DEFAULT，
兼容 SQLAlchemy 预取序列值并显式写入的行为，避免 PendingRollbackError。
"""

from alembic import op
from sqlalchemy import text

from common.utils.alembic_helpers import table_exists

revision = "20260508001"
down_revision = "20260316001"
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    if table_exists(conn, "chat_execution_trace"):
        conn.execute(
            text("ALTER TABLE chat_execution_trace ALTER COLUMN id SET GENERATED BY DEFAULT")
        )


def downgrade():
    conn = op.get_bind()
    if table_exists(conn, "chat_execution_trace"):
        conn.execute(
            text("ALTER TABLE chat_execution_trace ALTER COLUMN id SET GENERATED ALWAYS")
        )
