"""057_fix_identity_generated_always

将所有表的 id 列从 GENERATED ALWAYS 改为 GENERATED BY DEFAULT，
兼容 SQLAlchemy 预取序列值并显式写入的行为，避免 GeneratedAlways 报错。
修复完成后对齐所有序列值，防止因 nextval() 不回滚导致的序列漂移。
"""

from alembic import op
from sqlalchemy import text

from common.utils.alembic_helpers import table_exists

revision = "20260508001"
down_revision = "20260316001"
branch_labels = None
depends_on = None


TABLES = [
    "chat",
    "chat_record",
    "chat_log",
    "chat_execution_trace",
    "error_query_record",
    "core_datasource",
    "core_table",
    "core_field",
    "data_training",
    "terminology",
    "custom_prompt",
    "ds_permission",
    "ds_rules",
]


def upgrade():
    conn = op.get_bind()
    for table in TABLES:
        if not table_exists(conn, table):
            continue
        # 1) GENERATED ALWAYS → GENERATED BY DEFAULT
        conn.execute(
            text(f"ALTER TABLE {table} ALTER COLUMN id SET GENERATED BY DEFAULT")
        )
        # 2) 对齐序列值，修复 nextval() 不回滚导致的序列漂移
        row = conn.execute(
            text(
                f"SELECT pg_get_serial_sequence('{table}', 'id') AS seq"
            )
        ).first()
        seq_name = getattr(row, "seq", None) if row else None
        if seq_name:
            conn.execute(
                text(
                    f"SELECT setval(:seq, COALESCE((SELECT MAX(id) FROM {table}), 0) + 1, false)"
                ).bindparams(seq=seq_name)
            )


def downgrade():
    conn = op.get_bind()
    for table in reversed(TABLES):
        if not table_exists(conn, table):
            continue
        conn.execute(
            text(f"ALTER TABLE {table} ALTER COLUMN id SET GENERATED ALWAYS")
        )
